### ISSUE TITLE
Work out how to set group permissions

### ISSUE THREAD

**Issue by iangow** [mccgr/edgar#20]
I guess a lot of my code breaks once we go to a multi-user setting. Specifically, file that you have downloaded have ownership `bdcallen:bdcallen`:

```
igow@igow-z640:/home/shared/edgar/data/102909$ ls -hlt
total 240M
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005345.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005347.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-004773.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005349.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005350.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005340.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005348.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005346.txt
-rw-r--r-- 1 bdcallen bdcallen  35K Jun  8 09:40 0000932471-17-005344.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-005343.txt
-rw-r--r-- 1 bdcallen bdcallen  46K Jun  8 09:40 0000932471-17-004777.txt
...
```

But when I try to modify these files, I get permission errors.

I think the simplest way to tackle this would be to change group ownership and give write permissions to the group.

```
sudo chown -R igow:mccgr 102909
sudo chmod -R g+w 102909
```

After this, `mccgr` (this includes you and me) can write to these locations.

```
igow@igow-z640:/home/shared/edgar/data/102909$ ls -hlt
total 243M
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005345.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005347.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-004773.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005349.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005350.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005340.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005348.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005346.txt
-rw-rw-r-- 1 igow mccgr  35K Jun  8 09:40 0000932471-17-005344.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005343.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-004777.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005342.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005341.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005339.txt
-rw-rw-r-- 1 igow mccgr  46K Jun  8 09:40 0000932471-17-005338.txt
...
```
My question is: How can we set group ownership and `g+w` during the process of downloading these data?

**Comment by iangow** [comment]
Note that this permissions issue was causing files not to be downloaded using `get_13D_filings.R` and, without the files, `extract_cusips.R` doesn't work.

**Comment by bdcallen** [comment]
@iangow I'm guessing this one can be closed?

**Comment by iangow** [comment]
> @iangow I'm guessing this one can be closed?

Not sure we have answered this (from above):

> My question is: How can we set group ownership and `g+w` during the process of downloading these data?

**Comment by iangow** [comment]
> > @iangow I'm guessing this one can be closed?
> 
> Not sure we have answered this (from above):
> 
> > My question is: How can we set group ownership and `g+w` during the process of downloading these data?

@bdcallen ?

**Comment by bdcallen** [comment]
@iangow  I just tested the above on a file `tests.R` in my directory

```
-rw-r--r-- 1 bdcallen bdcallen     2043 Jan 24 15:13 tests.R
```

then doing

```
bdcallen@igow-z640:~/edgar$ chmod g+w tests.R
```

I got

```
-rw-rw-r-- 1 bdcallen bdcallen     2043 Jan 24 15:13 tests.R
```

So the group permission has indeed changed, but the group is still set to `bdcallen`. Thus we need a command to change the group for the file too. This can be done using chgrp. Doing

```
bdcallen@igow-z640:~/edgar$ chgrp mccgr tests.R
```

led to

```
-rw-rw-r-- 1 bdcallen mccgr        2043 Jan 24 15:13 tests.R
```

The changed permissions for the group remain. 

Thus, I think we can close this now.

**Comment by iangow** [comment]
@bdcallen I know that permissions can be changed in that way. The question is: How do we ensure that files added (by the cron job, etc.) get `mccgr` group ownership. Perhaps something needs to be added to the script for that.
