### ISSUE TITLE
Decide whether `tab_index` is redundant

### ISSUE THREAD

**Issue by bdcallen** [mccgr/edgar#47]
@iangow As I mentioned, I made a change to the code so that a variable called `tab_index` was kept track of in `forms345_table1`, `forms345_table2`, and `forms345_footnote_indices`. This variable contains information on the number of the instance of 'derivativeTable' or 'nonDerivativeTable' from list of nodes 
extracted using getNodeSet(xml_root, 'derivativeTable') and getNodeSet(xml_root, 'nonDerivativeTable') respectively. For instance, if you look inside `get_nonDerivativeTable_footnotes`

```r
if(num_tab <- length(non_derivative_table <- getNodeSet(xml_root, 'nonDerivativeTable'))) {

        non_deriv_tranhold_df <- data.frame(matrix(nrow = 0, ncol = 4))
        colnames(non_deriv_tranhold_df) <- c('tab_index', 'seq', 'footnote_variable', 'footnote_index')

        for(i in 1:num_tab) {

            non_deriv_tranhold_i <- getNodeSet(non_derivative_table[[i]], c('nonDerivativeTransaction', 'nonDerivativeHolding'))
            part <- get_table_footnotes_df(non_deriv_tranhold_i)
            if(nrow(part)) {

                part$tab_index <- i
                non_deriv_tranhold_df <- bind_rows(non_deriv_tranhold_df, part)

            }

        }
```
you see that there is no assumption made on how many `nonDerivativeTable` nodes there are (I previously wrote code assuming only one node), and that if there are multiple nodes, these nodes are looped over from the resultant list `non_derivative_table`, and their indices within `non_derivative_table` are kept track of in `tab_index`. So if there are multiple nodes, the entries in the dataframe will first have tab_index = 1, seq = 1, 2, 3 ...., then tab_index = 2, seq = 1, 2, 3, ...., and so on. 

I highly suspect, however, that my initial assumption of there only ever being at most one 'nonDerivativeTable' node and at most one `derivativeTable` node is essentially correct. Over a million filings or so, I have yet to encounter a case with `tab_index > 1` (the information on the number of each type of node is also kept track of in `forms345_xml_process_table`, in variables `num_non_derivative_tables` and `num_derivative_tables`). I still think it is worth going through the whole set however, to see if there are any exceptions at all. After this though, if the assumption holds, I think we should drop `tab_index` in all the relevant tables.

**Comment by iangow** [comment]
> After this though, if the assumption holds, I think we should drop `tab_index` in all the relevant tables.

Does this imply that there are feasible simplifications to the data beyond dropping `tab_index`?

**Comment by bdcallen** [comment]
> Does this imply that there are feasible simplifications to the data beyond dropping `tab_index`?

No. The field `tab_index` is only correlated with how many `derivativeTable` and `nonDerivativeTable` nodes there are, not on the underlying subnodes (like `derivativeHolding`, `derivativeTransaction` and so on).

**Comment by bdcallen** [comment]
```
crsp=> SELECT COUNT(*) FROM edgar.forms345_table1
crsp-> WHERE CAST(tab_index AS integer) = 1;
  count   
----------
 18652219
(1 row)

crsp=> SELECT COUNT(*) FROM edgar.forms345_table1
WHERE CAST(tab_index AS integer) != 1;
 count 
-------
     0
(1 row)

crsp=> SELECT COUNT(*) FROM edgar.forms345_table1
WHERE CAST(tab_index AS integer) IS NULL;
 count  
--------
 123975
(1 row)

crsp=> SELECT COUNT(*) FROM edgar.forms345_table2;
  count  
---------
 9063193
(1 row)


crsp=> SELECT COUNT(*) FROM edgar.forms345_table2
WHERE CAST(tab_index AS integer) = 1;
  count  
---------
 8989100
(1 row)

crsp=> SELECT COUNT(*) FROM edgar.forms345_table2
WHERE CAST(tab_index AS integer) != 1;
 count 
-------
     0
(1 row)

crsp=> SELECT COUNT(*) FROM edgar.forms345_table2
WHERE CAST(tab_index AS integer) IS NULL;
 count 
-------
 74093
```

Still seems this field is only ever 1 or NULL (by the way, I don't know why the underlying field is of type text at the moment).

**Comment by iangow** [comment]
I think fixing the data types for the Forms 3/4/5 tables (create an issue for this; though, the data types seem OK below) might be a higher priority than sorting out `tab_index`, but it would seem to be fine to just delete this column and make it so the code doesn't retain it in future.

 ``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)
pg <- dbConnect(RPostgres::Postgres())

rs <- dbExecute(pg, "SET work_mem='3GB'")
rs <- dbExecute(pg, "SET search_path TO edgar")

forms345_table1 <- tbl(pg, "forms345_table1")
forms345_table2 <- tbl(pg, "forms345_table2")

forms345_table1
#> # Source:   table<forms345_table1> [?? x 20]
#> # Database: postgres [igow@10.101.13.99:5432/crsp]
#>    file_name document form_type transactionOrHo…   seq tab_index
#>    <chr>     <chr>    <chr>     <chr>            <int> <chr>    
#>  1 edgar/da… form4.x… 4         Transaction          1 1        
#>  2 edgar/da… form4.x… 4         Holding              1 1        
#>  3 edgar/da… form4.x… 4         Transaction          1 1        
#>  4 edgar/da… form4.x… 4         Holding              2 1        
#>  5 edgar/da… form4.x… 4         Holding              3 1        
#>  6 edgar/da… form4.x… 4         Holding              4 1        
#>  7 edgar/da… form4.x… 4         Transaction          1 1        
#>  8 edgar/da… form4.x… 4         Holding              2 1        
#>  9 edgar/da… form4.x… 4         Holding              3 1        
#> 10 edgar/da… form4.x… 4         Holding              4 1        
#> # … with more rows, and 14 more variables: securityTitle <chr>,
#> #   transactionDate <date>, deemedExecutionDate <date>,
#> #   transactionFormType <chr>, transactionCode <chr>,
#> #   equitySwapInvolved <lgl>, transactionTimeliness <chr>,
#> #   transactionShares <dbl>, transactionPricePerShare <dbl>,
#> #   transactionAcquiredDisposedCode <chr>,
#> #   sharesOwnedFollowingTransaction <dbl>,
#> #   valueOwnedFollowingTransaction <dbl>, directOrIndirectOwnership <chr>,
#> #   natureOfOwnership <chr>
 
forms345_table1 %>% count()
#> # Source:   lazy query [?? x 1]
#> # Database: postgres [igow@10.101.13.99:5432/crsp]
#>   n       
#>   <int64> 
#> 1 18783784
forms345_table1 %>% count(tab_index)
#> # Source:   lazy query [?? x 2]
#> # Database: postgres [igow@10.101.13.99:5432/crsp]
#>   tab_index n       
#>   <chr>     <int64> 
#> 1 1         18659809
#> 2 <NA>        123975

forms345_table2 %>% count()
#> # Source:   lazy query [?? x 1]
#> # Database: postgres [igow@10.101.13.99:5432/crsp]
#>   n      
#>   <int64>
#> 1 9067113
forms345_table2 %>% count(tab_index)
#> # Source:   lazy query [?? x 2]
#> # Database: postgres [igow@10.101.13.99:5432/crsp]
#>   tab_index n      
#>   <chr>     <int64>
#> 1 1         8993020
#> 2 <NA>        74093
```

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bdcallen** [comment]
@iangow I think we just close this
