### ISSUE TITLE
Create README file forms345.md

### ISSUE THREAD

**Issue by bdcallen** [mccgr/edgar#48]
@iangow As discussed in previous posts and emails, we wish to write some documentation for the set of code and tables pertaining to Forms 3, 4 and 5.

**Comment by iangow** [comment]
Perhaps put the "`form345`" code in a `form345` subdirectory and put the documentation in `readme.md` in that folder.

**Comment by bdcallen** [comment]
@iangow I'm just wondering what the difference is between `transactionDate` and `deemedExecutionDate` is on Tables 1 and 2 on Forms 3, 4 and 5. The SEC's guide does not really give an explicit definition for each variable in the technical guide.

**Comment by iangow** [comment]
If it's not obvious, just pass over that for now. One possibility would be to look for cases where they differ and see if there is a logical explanation (I assume that they are often the same, though in this case, one might be `NA`/`NULL`/`None`).

**Comment by bdcallen** [comment]
@iangow I think if you're happy with the current README, `forms345.md`, we should close this issue.

**Comment by iangow** [comment]
Sure. Good for now. Later on we might do some "user testing" of the documentation.
