### ISSUE TITLE
Scrape filing docs

### ISSUE THREAD

**Issue by iangow** [mccgr/edgar#49]
@bdcallen 

I tweaked the code for scraping "`filing_docs`" to limit it to the first table. This is to handle cases like [this](https://www.sec.gov/Archives/edgar/data/1046404/000087183918000061/0000871839-18-000061-index.html).

Are you aware of situations where this will cause problems?

**Comment by iangow** [comment]
[Here](https://github.com/iangow-public/edgar/commit/a3233f3ded89ba103d20088dda13ed4859ccb7aa) is the commit with the relevant tweak.

**Comment by iangow** [comment]
I dumped the version of the table on the MCCGR server onto my server in Boston (`iangow.me`) and I'm running the code there (I can dump the completed table back to the MCCGR server when it is done).

I think that ideally `filing_docs` would be comprehensive (all filings) and updated regularly (using a cron job or something like that).

**Comment by bdcallen** [comment]
@iangow Are we able to close this?
