### ISSUE TITLE
Back up data for form345 tables

### ISSUE THREAD

**Issue by iangow** [mccgr/edgar#50]
@bdcallen I think the best backup strategy might be to copy the table to my Boston-based server and then backup the whole `edgar` schema. I can help you will this, but will need you to tell me which `form345`-related tables on the MCCGR server should be backed up and when they are ready to go.

**Comment by bdcallen** [comment]
@iangow Trying to do some stuff before I say it's ready to backup. I just downloaded the '3/A's, '4/A's and '5/A's last night, as I forgot to include them initially. There's a small number of filings which failed to be fully processed the first time around, which I will process today. I just got these types of error messages
```
> library(XML)
Error: package or namespace load failed for ‘XML’:
 package ‘XML’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
> library(rjson)
Error: package or namespace load failed for ‘rjson’:
 package ‘rjson’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
> library(RCurl)
Loading required package: bitops
Error: package or namespace load failed for ‘RCurl’:
 package ‘RCurl’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
> library(dplyr)
Error: package or namespace load failed for ‘dplyr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘Rcpp’ 0.12.16 is being loaded, but >= 0.12.19 is required
> library(lubridate)
Error: package or namespace load failed for ‘lubridate’:
 package ‘Rcpp’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```
Was R updated last night?

**Comment by iangow** [comment]
Sorry. I was updated this morning. If you restart the R session and try again, it should work.

**Comment by iangow** [comment]
@bdcallen Did you sort this out?

**Comment by bdcallen** [comment]
@iangow I've managed to process all but six of the xml documents. I've tried to run the program on this last batch a few times with no success. It seems these are failing due to an inconsistency in the urls, as get_xml_root is failing
```
> i = 1
> file_name <- form345_xml_docs_to_process$file_name[i]
> document <- form345_xml_docs_to_process$document[i]
> form_type <- form345_xml_docs_to_process$form_type[i]
> xml_root <- get_xml_root(file_name, document)
> xml_root
[1] NA
> i = 1
> file_name <- form345_xml_docs_to_process$file_name[i]
> document <- form345_xml_docs_to_process$document[i]
> form_type <- form345_xml_docs_to_process$form_type[i]
> xml_root <- get_xml_root(file_name, document)
> xml_root
[1] NA
> get_filing_document_url(file_name, document)
[1] "https://www.sec.gov/Archives/edgar/data/1200393/000100547703001498/edgar123.xml"
> file_name
[1] "edgar/data/1200393/0001005477-03-001498.txt"
> document
[1] "edgar123.xml"
```

The url based on the `file_name` and `document` for the first of these files should be [this](https://www.sec.gov/Archives/edgar/data/1200393/000100547703001498/edgar123.xml), with the CIK in the url being that of the reporting owner, but if you look at the page for the filing, the url of xml document in the link is actually [this](https://www.sec.gov/Archives/edgar/data/790818/000100547703001498/edgar123.xml), with everything the same, except for the CIK being that for the issuer. It's a similar story with the other five rogue filings.

**Comment by bdcallen** [comment]
@iangow I think I will make a small issue for this and leave them in the `forms345_xml_fully_processed` table with `fully_processed = FALSE`, for now.

**Comment by iangow** [comment]
This should really be fixed in `filing_docs`, but I think we don't want to do this just yet. I think for now the best thing to do would be to trap 404 errors, etc., and populate a table with a list of these that 

1. We can come back to later, and
2. Your `form345` code can use to skip over these for now.

**Comment by iangow** [comment]
> @iangow I think I will make a small issue for this and leave them in the `forms345_xml_fully_processed` table with `fully_processed = FALSE`, for now. 

Great. Ideally the code would trap the errors created by these filings and populate that table automatically. But it's OK for now to add these "manually".

**Comment by iangow** [comment]
I see they're already there:

```
crsp=# SELECT * FROM edgar.forms345_xml_fully_processed WHERE NOT fully_processed LIMIT 10;
                  file_name                  |          document           | fully_processed 
---------------------------------------------+-----------------------------+-----------------
 edgar/data/1200393/0001005477-03-001498.txt | edgar123.xml                | f
 edgar/data/1214608/0001334516-07-000030.txt | edgar.xml                   | f
 edgar/data/1190308/0001177702-03-000013.txt | c0001190308d20030509f4f.xml | f
 edgar/data/1230977/0000016058-12-000069.txt | edgar.xml                   | f
 edgar/data/1008790/0001209191-05-060799.txt | doc4.xml                    | f
 edgar/data/1230977/0000016058-13-000042.txt | edgar.xml                   | f
(6 rows)
```

**Comment by bdcallen** [comment]
@iangow I have just done the following tests on the data.

```
> query <- "SELECT COUNT(*) FROM edgar.forms345_xml_process_table WHERE got_xml = FALSE OR got_header = FALSE OR got_rep_own = FALSE 
+           OR got_table1 = FALSE OR got_table2 = FALSE OR got_footnotes = FALSE OR got_footnote_indices = FALSE 
+           OR got_signatures = FALSE OR wrote_header = FALSE OR wrote_rep_own = FALSE OR wrote_table1 = FALSE 
+           OR wrote_table2 = FALSE OR wrote_footnotes = FALSE OR wrote_footnote_indices = FALSE 
+           OR wrote_signatures = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_header AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_table1 AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_table2 AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_reporting_owners AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_signatures AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_footnotes AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_footnote_indices AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0

> query <-    "SELECT COUNT(*) FROM edgar.forms345_xml_fully_processed AS a INNER JOIN edgar.forms345_xml_process_table AS b
+              ON a.file_name = b.file_name AND a.document = b.document
+              WHERE a.fully_processed = FALSE"
> 
> dbGetQuery(pg, query)
  count
1     0
```
There are no partial failures among any of the filing documents, and there is no record in any of the other tables for the entries in `forms345_xml_fully_processed` for which `fully_processed` is FALSE.

**Comment by iangow** [comment]
You can use `dplyr` to make complicated SQL automagically:

``` r
library(DBI)
library(dplyr, warn.conflicts = FALSE)

pg <- dbConnect(RPostgres::Postgres())
rs <- dbExecute(pg, "SET work_mem TO '3GB'") 
rs <- dbExecute(pg, "SET search_path TO edgar, public")

forms345_xml_process_table <- tbl(pg, "forms345_xml_process_table")
forms345_xml_process_table %>%
    filter_at(vars(matches("^(got|wrote)_")), any_vars(not(.)))
#> # Source:   lazy query [?? x 28]
#> # Database: postgres [igow@10.101.13.99:5432/crsp]
#> # … with 28 variables: file_name <chr>, document <chr>, form_type <chr>,
#> #   got_xml <lgl>, got_header <lgl>, got_rep_own <lgl>, got_table1 <lgl>,
#> #   num_non_derivative_tables <int>, num_non_derivative_tran <dbl>,
#> #   num_non_derivative_hold <dbl>, num_non_derivative_sec <int>,
#> #   total_non_derivative_nodes <dbl>, got_table2 <lgl>,
#> #   num_derivative_tables <int>, num_derivative_tran <dbl>,
#> #   num_derivative_hold <dbl>, num_derivative_sec <int>,
#> #   total_derivative_nodes <dbl>, got_footnotes <lgl>,
#> #   got_footnote_indices <lgl>, got_signatures <lgl>, wrote_header <lgl>,
#> #   wrote_rep_own <lgl>, wrote_table1 <lgl>, wrote_table2 <lgl>,
#> #   wrote_footnotes <lgl>, wrote_footnote_indices <lgl>,
#> #   wrote_signatures <lgl>
```

<sup>Created on 2019-01-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by iangow** [comment]
@bdcallen So I think the code above (just edited) does all the tests you ran.

**Comment by bdcallen** [comment]
@iangow Ideally, the rows in `edgar.forms345_header` are in one to one correspondence with those of `edgar.forms345_xml_fully_processed`. Checking the first of these tables, 

```
> query <- "SELECT COUNT((file_name, document)) FROM  edgar.forms345_header"
> dbGetQuery(pg, query)
    count
1 7413307
> query <- "SELECT COUNT(file_name) FROM  edgar.forms345_header"
> dbGetQuery(pg, query)
    count
1 7413307
> query <- "SELECT COUNT(DISTINCT (file_name, document)) FROM  edgar.forms345_header"
> dbGetQuery(pg, query)
    count
1 7413304
> query <- "SELECT COUNT(DISTINCT file_name) FROM  edgar.forms345_header"
> dbGetQuery(pg, query)
    count
1 7413304
```
one sees that the file names are one to one with the individual xml documents, and that there are a few duplicates in header. Doing the same process for the latter, we get 

```
> query <- "SELECT COUNT((file_name, document)) FROM edgar.forms345_xml_fully_processed WHERE fully_processed"
> dbGetQuery(pg, query)
    count
1 7413309
> query <- "SELECT COUNT(file_name) FROM edgar.forms345_xml_fully_processed WHERE fully_processed"
> dbGetQuery(pg, query)
    count
1 7413309
> query <- "SELECT COUNT(DISTINCT (file_name, document)) FROM edgar.forms345_xml_fully_processed WHERE fully_processed"
> dbGetQuery(pg, query)
    count
1 7413306
> query <- "SELECT COUNT(DISTINCT file_name) FROM edgar.forms345_xml_fully_processed WHERE fully_processed"
> dbGetQuery(pg, query)
    count
1 7413306
```
so we get the same number of duplicates (3), but there are 2 more unique filings which aren't in `forms345_header`. Doing

```sql
SELECT * FROM edgar.forms345_xml_fully_processed AS a
LEFT JOIN edgar.forms345_header AS b 
ON a.file_name = b.file_name
WHERE a.fully_processed = TRUE 
AND b."issuerCik" IS NULL
```
one finds that these two filings are [edgar/data/1000697/0001127602-17-001023.txt](https://www.sec.gov/Archives/edgar/data/1000697/000112760217001023/0001127602-17-001023-index.htm) and [edgar/data/1000697/0001127602-17-001025.txt](https://www.sec.gov/Archives/edgar/data/1000697/000112760217001025/0001127602-17-001025-index.htm), both with `document` equal to `form4.xml`. One can check that these two file names are indeed not in `forms345_header`, but there are entries for these filings in some of the other tables (table1, table2, signatures, reporting_owners). I'm not sure why this has happened in these two cases, though just trying
```r
> file_name <- "edgar/data/1000697/0001127602-17-001025.txt"
> document <- "form4.xml"
> form_type <- "4"
> xml_root <- get_xml_root(file_name, document)
```
I got 
```
Opening and ending tag mismatch: p line 51 and P
Opening and ending tag mismatch: br line 50 and div
Opening and ending tag mismatch: p line 34 and body
Opening and ending tag mismatch: div line 24 and html
Premature end of data in tag body line 22
Premature end of data in tag html line 2
```
and a result of `xml_root = NA` .

**Comment by bdcallen** [comment]
@iangow What was really odd about the discrepancy just above was that `get_xml_root` sometimes did in fact work to get the underlying xml (though most times it didn't). So I ended up doing these ones "manually"; once I got the xml_root, I did the various parts inside `process_345_filing`, wrote the corresponding results to `forms_345_xml_process_table`, then did
```r
query <- "INSERT INTO edgar.forms345_xml_fully_processed VALUES ('edgar/data/1000697/0001127602-17-001023.txt', 'form4.xml', TRUE)"
dbGetQuery(pg, query)

query <- "INSERT INTO edgar.forms345_xml_fully_processed VALUES ('edgar/data/1000697/0001127602-17-001025.txt', 'form4.xml', TRUE)"
dbGetQuery(pg, query)
```

**Comment by iangow** [comment]
@bdcallen 

*I am running the backup (to my Boston server) now.*

It seems you have an account on my other server with `edgar` privileges. So you could do the backup yourself. You'd just need to log into `10.101.13.99` and run the following:

```
pg_dump --format custom -h 10.101.13.99 -d crsp --table edgar.filing_docs | pg_restore -h iangow.me -d crsp --clean
```

Because I've ran this a couple of days ago, there are tables already there, so I added `--clean` to the command I ran a couple of days ago. I am running the code in a terminal window inside RStudio Server, as that means the command will run even if I disconnect my laptop from the network (I think `nohup` or something might also work if put around the whole command), but this approach is pretty easy and robust. You could also put `localhost` in place of `10.101.13.99` if logged into `10.101.13.99`, but this probably makes no practical difference.

**Comment by iangow** [comment]
@bdcallen Ouch. I just wiped out the copy of `filing_docs` on my Boston server by using the wrong command in the comment above (now corrected), so I now have to revert to the one on `10.101.13.99`, which sets me back a couple of days. Anyway, hopefully it's done by early next week (I am scraping every filing).

**Comment by iangow** [comment]
I was seeing the consequences this error message myself with the `scrape_filing_docs.R` code. Using 30 cores just triggers this and populates the table with garbage. I dialed it back to 6 cores and this issue has gone away.

**Comment by iangow** [comment]
```
pg_dump -d crsp -h localhost --format custom --schema edgar > ~/Dropbox/pg_private/edgar.backup 
```

Now I just need to get the URL for the Dropbox file.

**Comment by bdcallen** [comment]
@iangow Is this one done?

**Comment by iangow** [comment]
@dingtq I think @bdcallen may need to ask someone in Research Platform Services for help on a viable backup strategy. A shared network drive might be fine, though I think that ideally we'd have some history of backups. If UniMelb can support Dropbox, then what I did above may be an option (though you'd need to set up Dropbox on the MCCGR machine).

**Comment by dingtq** [comment]
Ian:

We will check it out soon.

BTW, I send email to Bianca Durrant at bdurrant@unimelb.edu.au regarding Directedgar reinstallation but haven’t got any response yet. Did I get the contact right?

Ben:

Do you have contact of Research platform service? We can have a chat for this when you are in office or through email.

-Tony
________________________________

**Comment by iangow** [comment]
@dingtq @bdcallen Maybe reach out to someone in Research Platform Services to get the status of their operation at the moment. Basically we want a few GB of space (maybe 100 or so) to backup the whole database. I will close *this* issue … I'm currently backing up the data to one of my two Boston servers. (I can easily give you access … they are both at `iangow.me` and in databases named `crsp`. One is on port `5432`; the other on port `5434`.

**Comment by dingtq** [comment]
@iangow Thank you! We will check it out. @bdcallen, maybe you can try the person that you contacted last time first. If it does not work, I can reach out to Bianca to see how we can get this done.

**Comment by iangow** [comment]
OK. I have backed up the data to my server here for now. I will put a backup on Dropbox too. @bdcallen If you could create a "Speak to Research Platform Services about backup" issue on `mccgr/misc` that would be great. I will close this one now.
