### ISSUE TITLE
Address multiple tables in `filing_docs`.

### ISSUE THREAD

**Issue by iangow** [mccgr/edgar#51]

**Comment by iangow** [comment]
@bdcallen You may have already addressed this issue, which related to cases when there are multiple tables in the page listing "filing docs" for a given filing. Perhaps there is another related issue that we've closed. If you can confirm this, then just close this issue. If not and you can't see what's going on with it, then re-assign the issue to me and I will take a look at perhaps making a better issue.

**Comment by bdcallen** [comment]
@iangow From memory, yes, this is a reference to the second tables in the filing page which contain all sorts of xml files. There a two previous issues relating to this #12 and #16. You closed #16, suggesting that we were not interested in the xml files at the time, so I seem to have closed #12 in response. So I'm going to close this for now. Perhaps you can reopen the other issues if you see some reason to scrape the second table.

**Comment by iangow** [comment]
> @iangow From memory, yes, this is a reference to the second tables in the filing page which contain all sorts of xml files. There a two previous issues relating to this #12 and #16. You closed #16, suggesting that we were not interested in the xml files at the time, so I seem to have closed #12 in response. So I'm going to close this for now. Perhaps you can reopen the other issues if you see some reason to scrape the second table.

Thanks. This was not a well-formed issue in the first place (I should have included problematic URLs in the issue at the outset).
