### ISSUE TITLE
Find out memory requirements for server logs

### ISSUE THREAD

**Issue by bdcallen** [mccgr/edgar#57]
@iangow @jamespkav As discussed in emails.

**Comment by jamespkav** [comment]
@bdcallen I don't think I have that email? What was the outcome? Can we run the code without filling up the drive?

**Comment by bdcallen** [comment]
@jamespkav I'll send you the email now

**Comment by jamespkav** [comment]
Brilliant. thanks @bdcallen . If I have any questions I'll let you know.

**Comment by iangow** [comment]
@bdcallen Is this still an issue?

**Comment by bdcallen** [comment]
@iangow No. Let's close.
