### ISSUE TITLE
Fix $EDGAR_CODE_DIR

### ISSUE THREAD

**Issue by iangow** [mccgr/edgar#68]
The environment variable `EDGAR_CODE_DIR` should be set in the cron job and there should be a `cd $EDGAR_CODE_DIR` there. This should *not* appear in code in this repository.

**Comment by bdcallen** [comment]
@iangow Ok, I have made the changes to the bash scripts, and changed my crontab to 
```
26 17 * * * $CODE_DIR/./asx_prev_day_cronjob.sh
00 21 * * * cd $EDGAR_CODE_DIR && ./update_edgar.sh
00 0 * * * cd $EDGAR_CODE_DIR && ./update_forms_345_tables.sh
00 6 * * 5 $ABN_LOOKUP_DIR/./abn_lookup_cronjob.sh
00 3 * * 4 $ASIC_DIR/./asic_bulk_extract_cronjob.sh
```

Will this affect the other cronjobs in the crontab?

**Comment by iangow** [comment]
Checking [one of these](https://github.com/search?q=ASIC_DIR+user%3Amccgr&type=Code), it seems that `ASIC_DIR` is still in the code. I think you should assume that the code is run from the root directory of the local repository. If that's `ASIC_DIR`, then there's no need to use `ASIC_DIR` in the code in the repository.

Links for:

- [`CODE_DIR`](https://github.com/search?q=CODE_DIR+user%3Amccgr&type=Code)
- [`EDGAR_CODE_DIR`](https://github.com/search?q=EDGAR_CODE_DIR+user%3Amccgr&type=Code)
- [`ABN_LOOKUP_DIR`](https://github.com/search?q=ABN_LOOKUP_DIR+user%3Amccgr&type=Code)
- [`ASIC_DIR`](https://github.com/search?q=ASIC_DIR+user%3Amccgr&type=Code)

**Comment by iangow** [comment]
I think each of the four above implies an issue like this one in the appplicable repository.

**Comment by bdcallen** [comment]
@iangow I agree. I will open issues for all of them, then fix them and close

**Comment by bdcallen** [comment]
@iangow Ok, this issue is fixed, as EDGAR_CODE_DIR no longer appears in the code in the repository. Closing now.
